"use client";
import Link from "next/link";
import {FormEvent,useMemo,useState,type CSSProperties} from "react";
import {HUNTER_COIN_PRICE,formatVnd,shopBundles,skins,spendMilestones,type SkinCollection} from "../data/catalog";
import {Brand,SiteHeader} from "./site-brand";
const BASE_PATH=process.env.NEXT_PUBLIC_BASE_PATH??"/website";
const labels:Record<"all"|SkinCollection,string>={all:"Tất cả",liger:"Liger",hero:"Nhân vật",legendary:"Huyền thoại",gacha:"Skin Gacha"};
function SkinRender({index,label}:{index:number;label:string}){const cols=4,rows=12,col=index%cols,row=Math.floor(index/cols);const style:CSSProperties={backgroundImage:`url(${BASE_PATH}/skin-renders/atlas-small.webp)`,backgroundSize:`${cols*100}% ${rows*100}%`,backgroundPosition:`${col*(100/(cols-1))}% ${row*(100/(rows-1))}%`};return <span className="skin-render" style={style} role="img" aria-label={label}/>}
type Order={title:string;amount:number;detail:string};
function Checkout({order,onClose}:{order:Order;onClose:()=>void}){const[name,setName]=useState("");const[ok,setOk]=useState(false);function submit(e:FormEvent){e.preventDefault();if(/^[A-Za-z0-9_]{3,16}$/.test(name))setOk(true)}return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="checkout-modal"><button className="modal-close" onClick={onClose}>×</button><p className="kicker">Đơn hàng SVFrame</p><h2>{order.title}</h2>{!ok?<form className="checkout-form" onSubmit={submit}><label>Tên Minecraft</label><input value={name} onChange={e=>setName(e.target.value.trim())} placeholder="Tên nhân vật" maxLength={16}/><button className="primary-button">Tạo nội dung thanh toán</button></form>:<div className="qr-box"><img src={`${BASE_PATH}/payment/qr.webp`} alt="QR ngân hàng"/><div><p>Người chơi: <b>{name}</b></p><p>Sản phẩm: <b>{order.detail}</b></p><p>Số tiền: <b>{formatVnd(order.amount)}</b></p><p>Nội dung: <code>{name} {order.title}</code></p><small>Gửi ảnh giao dịch cho quản trị viên để xác nhận và trao vật phẩm.</small></div></div>}</section></div>}
export default function Storefront(){const[filter,setFilter]=useState<"all"|SkinCollection>("all");const[order,setOrder]=useState<Order|null>(null);const list=useMemo(()=>skins.filter(s=>filter==="all"||s.collection===filter),[filter]);return <main><SiteHeader/>
<section className="hero section-shell"><div className="hero-copy"><p className="kicker">SVFrame Network · Cobblemon</p><h1>Skin thật.<br/>Render thật.<br/><span>Mua ngay trên web.</span></h1><p className="hero-lead">Skin lấy từ model và texture của server. Wiki dùng sprite để tra cứu nhanh; shop không dùng sprite Pokémon thay cho skin.</p><div className="hero-actions"><a className="primary-button" href="#skins">Xem skin <span>→</span></a><Link className="secondary-button" href="/wiki">Mở Wiki</Link></div><div className="hero-stats"><div><b>24</b><span>skin mua trực tiếp</span></div><div><b>24</b><span>skin trong Gacha</span></div><div><b>25.000₫</b><span>mỗi Hunter Coin</span></div></div></div><div className="hero-showcase"><div className="hero-render hero-render-main"><SkinRender index={19} label="Zygarde Gundam Freedom"/><div><small>Huyền thoại</small><strong>Zygarde · Gundam Freedom</strong></div></div><div className="hero-render hero-render-side hero-render-left"><SkinRender index={17} label="Palkia The Long Quiet"/><span>The Long Quiet</span></div><div className="hero-render hero-render-side hero-render-right"><SkinRender index={18} label="Rayquaza Xà Thần"/><span>Xà Thần</span></div></div></section>
<section className="quick-links"><div className="section-shell quick-links-grid"><div><span>Server</span><strong>poke.sv-frame.com</strong><small>Fabric 1.21.1 · Loader 0.18.4</small></div><Link href="/huong-dan"><span>Bộ cài</span><strong>Tải Full / Lite</strong><small>Xem hướng dẫn →</small></Link><Link href="/wiki"><span>Wiki</span><strong>897 Pokémon</strong><small>Tra biome →</small></Link><a href="#topup"><span>Nạp</span><strong>Hunter Coin</strong><small>QR ngân hàng →</small></a></div></section>
<section id="skins" className="content-section section-shell"><div className="section-head"><div><p className="kicker">Shop skin</p><h2>Model thật từ source server.</h2></div><p>Skin mua trực tiếp có giá HC. Skin Gacha được tách riêng và mở bằng chìa, không giả thành sản phẩm mua lẻ.</p></div><div className="filter-row">{(["all","liger","hero","legendary","gacha"] as const).map(k=><button className={filter===k?"active":""} onClick={()=>setFilter(k)} key={k}>{labels[k]}</button>)}</div><div className="skin-grid">{list.map(s=><article className="skin-card" key={s.id}><div className="skin-image"><SkinRender index={s.renderIndex} label={`${s.pokemon} ${s.name}`}/></div><div className="skin-info"><div><small>{s.pokemon}</small><h3>{s.name}</h3></div><span>{labels[s.collection]}</span></div><div className="skin-actions">{s.purchasable?<><span className="skin-price">{s.priceHC} HC · {formatVnd(s.priceHC*HUNTER_COIN_PRICE)}</span><button onClick={()=>setOrder({title:s.id,detail:`${s.pokemon} · ${s.name}`,amount:s.priceHC*HUNTER_COIN_PRICE})}>Mua</button></>:<span>Nhận từ Skin Gacha</span>}</div></article>)}</div></section>
<section id="bundles" className="content-section section-shell"><div className="section-head"><div><p className="kicker">Gói đổi FTB Quests</p><h2>Giá lấy theo quest server.</h2></div><p>Các gói dưới đây giữ nguyên mức HC và phần thưởng đang cấu hình.</p></div><div className="bundle-grid">{shopBundles.map(b=><article className="bundle-card" key={b.title}><p className="kicker">{b.priceHC} HC</p><h3>{b.title}</h3><ul>{b.rewards.map(r=><li key={r}>{r}</li>)}</ul><button className="primary-button" onClick={()=>setOrder({title:b.title,detail:b.title,amount:b.priceHC*HUNTER_COIN_PRICE})}>Chọn gói</button></article>)}</div></section>
<section id="milestones" className="content-section section-shell"><div className="section-head"><div><p className="kicker">Tích tiêu</p><h2>Nhận quà theo tổng HC đã dùng.</h2></div></div><div className="milestone-grid">{spendMilestones.map(m=><article className="milestone-card" key={m.amountHC}><p className="kicker">{m.amountHC} HC</p><h3>{m.title}</h3><ul>{m.rewards.map(r=><li key={r}>{r}</li>)}</ul></article>)}</div></section>
<section id="topup" className="topup-section section-shell"><div className="topup-copy"><p className="kicker">Nạp Hunter Coin</p><h2>25.000₫ <span>= 1 HC</span></h2><p>Chọn gói nạp rồi quét QR. Nội dung chuyển khoản được tạo theo tên Minecraft.</p></div><div className="topup-panel"><h3>Gói nạp nhanh</h3><div className="quantity-presets">{[1,5,10,20,40].map(v=><button key={v} onClick={()=>setOrder({title:`${v}HC`,detail:`Nạp ${v} Hunter Coin`,amount:v*HUNTER_COIN_PRICE})}>{v} HC<br/><small>{formatVnd(v*HUNTER_COIN_PRICE)}</small></button>)}</div></div></section>
<footer><div className="section-shell footer-grid"><Brand/><p>Shop và Wiki chính thức của SVFrame Network.</p><div><Link href="/#skins">Skin</Link><Link href="/huong-dan">Tải mod</Link><Link href="/wiki">Wiki</Link></div><span>© {new Date().getFullYear()} SVFrame Network</span></div></footer>{order&&<Checkout order={order} onClose={()=>setOrder(null)}/>}</main>}
